// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsV8qEeVEa0KLR7jHMplQfyETMCYrauYM',
    appId: '1:698066708498:web:39929ed8749968713cd0cb',
    messagingSenderId: '698066708498',
    projectId: 'projectforglobal',
    authDomain: 'projectforglobal.firebaseapp.com',
    storageBucket: 'projectforglobal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_nvb1tHe2Ycp4TmGbOrGWUH2pdDBoqEA',
    appId: '1:698066708498:android:f30dbb6f8f4db8ad3cd0cb',
    messagingSenderId: '698066708498',
    projectId: 'projectforglobal',
    storageBucket: 'projectforglobal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLiFS2PyumCxFnl_nAYmhlcXi4BuxBJk',
    appId: '1:698066708498:ios:dc83b967ad5cede23cd0cb',
    messagingSenderId: '698066708498',
    projectId: 'projectforglobal',
    storageBucket: 'projectforglobal.appspot.com',
    iosBundleId: 'com.example.globalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHLiFS2PyumCxFnl_nAYmhlcXi4BuxBJk',
    appId: '1:698066708498:ios:dc83b967ad5cede23cd0cb',
    messagingSenderId: '698066708498',
    projectId: 'projectforglobal',
    storageBucket: 'projectforglobal.appspot.com',
    iosBundleId: 'com.example.globalProject',
  );
}
